update timeout + add initial to csv
Signed-off-by: BorisV <borisv@armosec.io>

diff --git a/.github/workflows/sanity-check.yaml b/.github/workflows/sanity-check.yaml
--- a/.github/workflows/sanity-check.yaml
+++ b/.github/workflows/sanity-check.yaml
@@ -121,13 +121,21 @@ jobs:
                   --kwargs helm_branch=release \
                 deactivate
 
-              if [ $? != 0 ]; then
-                # append to local csv if test failed
-                timestamp=$(date +"%Y-%m-%d %H:%M:%S")
-                echo "$timestamp,0" >> ~/sanity_logs.csv
-              fi    
-              exit $?
+              # if [ $? != 0 ]; then
+              #   # append to local csv if test failed
+              #   timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+              #   echo "$timestamp,0" >> ~/sanity_logs.csv
+              # fi    
+              # exit $?
               
+        - name: Append to CSV if test failed in first time
+          if: steps.StepId1.outcome == 'failure'
+          run: |
+            # append to local csv if test failed
+            timestamp=$(date +"%Y-%m-%d %H:%M:%S")
+            echo "$timestamp,0" >> ~/sanity_logs.csv
+            eval sed\ s/\$/\\$'\n'/g\ ~/sanity_logs.csv | cat >> "logs/sanity_logs.csv"
+
         - name: run-tests-repeated
           if: ${{ inputs.RETRY_JOB == true }}
           id: StepId2
